{% set version = "0.20.11.7" %}

package:
  name: trash-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trash-cli/trash-cli-{{ version }}.tar.gz
  sha256: f27f05e0a151211f835277f19105a669b27908949cfd4770c4fa38ff94641c95

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - trashcli
  commands:
    - trash -h
    - trash-put -h
    - trash-list -h
    - trash-restore -h
    - trash-empty -h
    - trash-rm -h

about:
  home: https://github.com/andreafrancia/trash-cli
  license: GPL-2.0
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: Command line interface to FreeDesktop.org Trash.

extra:
  recipe-maintainers:
    - ocefpaf
