travis:
  secure:
    BINSTAR_TOKEN: WCj4Gz+oyFd6RdDiMFeYbBBOiUYxiDAORC7MPf7SadkKwnhCOVasecQZ1HLRHaiNGWTf/CCyA1T6UEoQRHZpiaPV0QJcjlxRC8M3PoIWKkV/k3BzyBQQP50T3bdhm1dOCeN5RY4NxyutsrEehVHcTKtmNdeSqXPvgYDj5ky8nWaY8QXnl72E2ZeLk/khCIlZ43tGHcVGx+yeNXnLN7I4e8cwMHjJ9pkJLPW4ScobaRttwNnV5/wYfLxpyBdvt6cUcUHO60lgaPadnYHrYBHiYBBvVZAQoCRI4QSmmnQMcLnWk74XSx5MWpKD76615U06vWNAFFo+/aTtMF/IDusstg5Ke3e9lBkyvk/KR8hW2bspY8i5LiDxyxVVpu6bfdwXSNNQjDTNAd3a6lP/r7KqEqr9KGhq9JePfV6pMiO7cTgfV/kHzVPvgm+oUDCBFyn/05WG2kIZ/GB3TG9f2spdfYo6X6na6DzFSSdrzseglxwL7Qd5HXdV3abO/erbwhLxQcYWcNUSjwoR9rCv6k3pMlYCbuk6oDcXKsPbYXnMdWtGHe7EnM/ty1geox9ZWXh/dVwFwdfbbxqG7Qf4KnOcs/TQmq4IoVdOCJYG/6RCl1xhFkXZpc5tBfvuqsZX50hVhu4ZeOl0D8Pi0HP+iAnXDYh6464Mg4nWUOHAK8YivVk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
