travis:
  secure:
    BINSTAR_TOKEN: nz1dxylB4MxlJ5SHCewLd2oE3ocjlV5OX/e1gp8BMU3n62NV/QxvvF0PqutDfc/8X92JbgEvct28s4dlpddana2v8cLpUj9XQ0UaRt2ID1Ivxv+5DHUTC74e4tETHcCoIVFFK6x+QCan2MtNdm/8baJJEMTyIEFEQRgruJqMA8/NUiYYRNpvykbHjlCF8OyjqHlDnmWk/hJzEEcdbcf4oB9iZmUcpAgM77dBEBRvk81TV6qxtJRijXSj5EOdlyKBQ68vP7N/yeYgN9jgMpXhTzG/Y7gf9kQzo/002uYvkuUrEb5zfyZhDUYyrecSVE41n6HyQNnn2v8+RJn90BEIlvbRjgYhZuQz02p17vX3OQ8hwbzaHs0TO+bON+suy6xT15GE31p9f+XZ8NVgrwloPuR2OaeXhjFDfpemLtKqvPS3BPzd90RGUW2VRrSvmCPKEhONLfxDp75vYqzWZcjbRVAT51XjZrSERbke52bdLc7FXv85P6t8GMBmqMd8lVeKvCwJAEkV7cZeui4fYomiJ9uv5VJiTj5qIQoTpwNU3Ad9HkTD67UrPL0qr/LF0u0i019oj+Uk5dmmJNKXKBDvaITqO0nV2u1CNA8IucxA3VtkLksY9qPqpTUdnVgedejIIuQS9nHM3or0etCaWxsWi6O/04gd5R3E+nRP65la168=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
